#!/usr/bin/env python3
"""Generate the builtin parameter table from a pinned CUE checkout.

    python3 tools/builtin-signatures.py <cue-source> > crates/cue-eval/src/stdlib/signatures.rs

Reads every generated `pkg/**/pkg.go` (the `pkg/tool` packages are commands,
not builtins) and records, per builtin, how its implementation reads each
argument: the `CallCtxt` accessor decides what a not-yet-concrete argument
means (see `internal/pkg/context.go`). The tests pin the table to the oracle
revision in tests/conformance/README.md.
"""
import re
import sys
from pathlib import Path

# CallCtxt accessor -> the parameter shape cue-rs judges an argument by.
ACCESSORS = {
    "String": "String",
    "Bytes": "Bytes",
    "Reader": "Bytes",
    "Bool": "Bool",
    "Int": "Int", "Int8": "Int", "Int16": "Int", "Int32": "Int", "Int64": "Int",
    "Rune": "Int", "Uint": "Int", "Uint8": "Int", "Byte": "Int", "Uint16": "Int",
    "Uint32": "Int", "Uint64": "Int", "BigInt": "Int",
    "Float64": "Number", "Decimal": "Number", "BigFloat": "Number",
    "Struct": "Struct",
    "List": "List", "Iter": "List", "CueList": "List",
    "StringList": "StringList",
    "DecimalList": "NumberList",
    "Value": "Value",
    "Schema": "Schema",
}
# A parameter the implementation never reads through an accessor.
KINDS = {
    "adt.StringKind": "String",
    "adt.BytesKind | adt.StringKind": "Bytes",
    "adt.IntKind": "Int",
    "adt.NumberKind": "Number",
    "adt.BoolKind": "Bool",
    "adt.ListKind": "List",
    "adt.StructKind": "Struct",
    "adt.TopKind": "Value",
}

# Sorting reads its list through a comparator, which is a template rather
# than data: an element it cannot order is the comparator's error.
OVERRIDES = {
    ("list", name): ["SortedList", "Schema"] for name in ("Sort", "SortStable", "IsSorted")
}

BLOCK = re.compile(r'\{\s*Name:\s*"(\w+)",\s*Params:\s*\[\]pkg\.Param\{(.*?)\n\t\t\},(.*?)\n\t\},?', re.S)
PARAM = re.compile(r"\{Kind: ([^,}]+)(, Value: \w+)?\}")
ACCESS = re.compile(r"\bc\.(\w+)\((\d+)\)")


def builtins(source: Path):
    for file in sorted(source.glob("pkg/**/pkg.go")):
        package = file.parent.relative_to(source / "pkg").as_posix()
        if package.startswith("tool"):
            continue
        text = file.read_text()
        for name, params, rest in BLOCK.findall(text):
            kinds = PARAM.findall(params)
            accessors = {int(i): a for a, i in ACCESS.findall(rest) if a in ACCESSORS}
            shapes = []
            for i, (kind, default) in enumerate(kinds):
                shape = ACCESSORS[accessors[i]] if i in accessors else KINDS[kind.strip()]
                shapes.append(shape)
            shapes = OVERRIDES.get((package, name), shapes)
            required = sum(1 for _, default in kinds if not default)
            validator = re.search(r"Result:\s*adt\.BoolKind\b", rest) is not None
            yield package, name, shapes, required, validator


def main():
    source = Path(sys.argv[1])
    rows = list(builtins(source))
    if len(rows) < 250:
        raise SystemExit(f"only {len(rows)} builtins parsed from {source}")
    out = [
        "//! Every builtin's parameters as the pinned CUE implementation reads them.",
        "//! Generated by `tools/builtin-signatures.py` from cue `pkg/**/pkg.go`; do not edit.",
        "",
        "use super::signature::{Param::*, Signature};",
        "",
        "#[rustfmt::skip]",
        "pub(crate) const SIGNATURES: &[Signature] = &[",
    ]
    for package, name, shapes, required, validator in rows:
        params = ", ".join(shapes)
        out.append(
            f'    Signature {{ package: "{package}", name: "{name}", params: &[{params}], '
            f"required: {required}, validator: {str(validator).lower()} }},"
        )
    out.append("];")
    print("\n".join(out))


main()
